version: "3.9"

networks:
  priv_network:
    name: priv_network
    driver: bridge

services:
  nginx : 
    container_name: nginx
    build: 
      context : "./requirements/nginx/"
      dockerfile: Dockerfile
    image: nginx
    env_file: ./.env
    ports:
      - "443:443"
    depends_on:
      - wordpress
    # volumes:
    #   - myapp:/usr/src/nginx
    restart: on-failure
    networks:
      - priv_network
  
  wordpress :
   container_name: wordpress
   build :
    context: "./requirements/wordpress_1/"
    dockerfile: Dockerfile
   image: wordpress
   env_file: ./.env
   # volumes:
   #   - myapp:/usr/src/wordpress
   restart: on-failure
   networks:
    - priv_network
   depends_on:
    - mariadb
   expose:
    - "9000"
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb/
    image: mariadb:42
    env_file: ./.env
    networks:
      - priv_network
    expose:
      - "3306"
    restart: unless-stopped

